services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
  promlens:   # To connect to prometheus, type in the URL box: http://localhost:9090
    image: "prom/promlens"
    ports:
      - "8080:8080"

volumes:
  grafana-storage:
