services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus

volumes:
  grafana-storage:
